# -*- coding: utf-8 -*-
"""BigDataStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIQJZYfK22mKB2_bO2cVrolxSgt8FaIh
"""


import streamlit as st
import pandas as pd
import plotly.express as px

# Load the sentiment dataframe
df = pd.read_csv("/content/sentiment_analysis_results.csv")  # Or use df_final_pd if directly in script

st.title("🗞️ News Sentiment Dashboard")

# Pie chart
st.subheader("Sentiment Distribution")
fig1 = px.pie(df, names='sentiment_label')
st.plotly_chart(fig1)

# Show recent headlines
st.subheader("Top Headlines with Sentiment")
st.dataframe(df[['title', 'sentiment_label']])

# (Optional) Sentiment over time
if 'publishedAt' in df.columns:
    df['publishedAt'] = pd.to_datetime(df['publishedAt'])
    fig2 = px.histogram(df, x='publishedAt', color='sentiment_label')
    st.subheader("Sentiment Over Time")
    st.plotly_chart(fig2)
